### ISSUE TITLE
Error when using Python3

### ISSUE THREAD

**Issue by bmoscon** [manahl/mockextras#5]
While using python3 and Mock 1.3.0, this unit test in arctic fails:

test_write_pandas_data_to_right_libraries

here in mockextras:

```
    def __init__(self, mock_fn):
        self._mock_fn = mock_fn
        if not _is_instance_mock(self._mock_fn):
>           raise RuntimeError("mock_fn must be an instance of Mock")
E           RuntimeError: mock_fn must be an instance of Mock
```

yet you can clearly see that mock_fn is indeed an instance of Mock:

```
mock_fn = <Mock name='mock._slice' id='139772101778000'>
```

when I printed the type of mock_fn, I got:

```
<class 'mock.mock.Mock'>
```

**Comment by burrowsa** [comment]
If your version of python has `unittest.mock` in the standard library then mockextras uses and supports that and does not support (the now considered a back port) `mock`. Otherwise it supports `mock`. I recomend you follow the same practice, you can do the import like:

    try:
        from unittest.mock import Mock
    except ImportError:
        from mock import Mock

**Comment by bmoscon** [comment]
thanks for the quick response, that did the trick! I didn't realize mock and unittest.mock were not compatible. I guess its not a 1 to 1 backport?
