### ISSUE TITLE
Storing parameters passed into mock methods for later use

### ISSUE THREAD

**Issue by paul-hammant** [manahl/mockextras#8]
```
from unittest import TestCase
from mock import Mock, call
from mockextras import stub, Store

class Foo:
    def __init__(self, bar):
        self.bar = bar
    def foooo(self, paramX):
        return bar.baaar(paramX * 3)

class FooTest(TestCase):
    def test_to_show_what_i_am_talking_about(self):
        store = Store()
        bar = Mock()
        bar.baaar.side_effect = stub((store.record_as("baaar_p0"), True))
        foo = new Foo(bar)
        foo.foooo(22)
        # I don't really want to assertEquals on it, but something 
        # more deterministic instead...
        self.assertEquals(66, store['baaar_p0'])
```

Of course this may be possible already, but the documentation does not show it.

Lastly, while I'm here - some of the examples in the documentation use plain 'assert'. Should be assertEquals throughout, IMO.

**Comment by burrowsa** [comment]
As a py.test user ```assert``` is how I asser in my tests but you are right, some reference to ```assertEquals``` might but useful for unittest users. I have raised. #9

**Comment by burrowsa** [comment]
I think this is more of question about mock, mockextras just provides a few extra bits on top of the standard mock library. Here is how I would do your example using mock and mockextra (although see the comment I don't think mockextras is required for this simple example).

    from unittest import TestCase
    from mock import Mock, call, ANY
    from mockextras import stub
    
    
    class Foo:
        def __init__(self, bar):
            self.bar = bar
        def foooo(self, paramX):
            return self.bar.baaar(paramX * 3)
    
    
    class FooTest(TestCase):
        def test_to_show_what_i_am_talking_about(self):
            bar = Mock()
            # If you don't care what is passed in you can specify the ANY matcher
            bar.baaar.side_effect = stub((ANY, True))
            # although of course in this simple example it would be better to write:
            # bar.baaar.return_value = True
            # and avoid using a stub and removed the need for mockextras

            # Create the class we want to test and then call it
            foo = Foo(bar)
            foo.foooo(22)
            
            # Now we can assert how bar.baaar was called
            bar.baaar.assert_called_once_with(66)
            
            # Or if we want to do something else with the value we can get it:
            arg_passed_to_baaar = bar.baaar.call_args[0][0]
            
            # You might also want to checkout bar.baaar.call_args_list and bar.mock_calls

**Comment by ph-hs** [comment]
Cool, thanks.
